# Generated by Django 3.0.3 on 2020-02-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('second', models.SmallIntegerField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
