# Generated by Django 3.0.3 on 2020-02-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendm', '0002_mail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
